In [1]:
#test comment
import pandas as pd

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
  
# data (as pandas dataframes) 
X = heart_disease.data.original 
y = heart_disease.data.targets 
  
# metadata 
print(heart_disease.metadata) 
  
# variable information 
heart_disease.data.variablesW

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. JÃ¡nosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sandhu, K. Guppy, S. Lee, V. Froelicher', 'venue': 'American Journal of Cardiology', 'year': 1989, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/a7d714f8f87bfc41351eb5ae1e5472f0ebbe0574', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '2756873', 'pmcid': None}, 'additional_info': {'summary': 'This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them.  In particular, the Cleveland database is the only one that has been used by ML researchers to date.  The "goal" field refers to the presence of heart disease in the patient.  It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).  \n   \nThe names and social security numbers of the patients were recently removed from the database, replaced with dummy values.\n\nOne file has been "processed", that one containing the Cleveland database.  All four unprocessed files also exist in this directory.\n\nTo see Test Costs (donated by Peter Turney), please see the folder "Costs" ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Only 14 attributes used:\r\n      1. #3  (age)       \r\n      2. #4  (sex)       \r\n      3. #9  (cp)        \r\n      4. #10 (trestbps)  \r\n      5. #12 (chol)      \r\n      6. #16 (fbs)       \r\n      7. #19 (restecg)   \r\n      8. #32 (thalach)   \r\n      9. #38 (exang)     \r\n      10. #40 (oldpeak)   \r\n      11. #41 (slope)     \r\n      12. #44 (ca)        \r\n      13. #51 (thal)      \r\n      14. #58 (num)       (the predicted attribute)\r\n\r\nComplete attribute documentation:\r\n      1 id: patient identification number\r\n      2 ccf: social security number (I replaced this with a dummy value of 0)\r\n      3 age: age in years\r\n      4 sex: sex (1 = male; 0 = female)\r\n      5 painloc: chest pain location (1 = substernal; 0 = otherwise)\r\n      6 painexer (1 = provoked by exertion; 0 = otherwise)\r\n      7 relrest (1 = relieved after rest; 0 = otherwise)\r\n      8 pncaden (sum of 5, 6, and 7)\r\n      9 cp: chest pain type\r\n        -- Value 1: typical angina\r\n        -- Value 2: atypical angina\r\n        -- Value 3: non-anginal pain\r\n        -- Value 4: asymptomatic\r\n     10 trestbps: resting blood pressure (in mm Hg on admission to the hospital)\r\n     11 htn\r\n     12 chol: serum cholestoral in mg/dl\r\n     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)\r\n     14 cigs (cigarettes per day)\r\n     15 years (number of years as a smoker)\r\n     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)\r\n     17 dm (1 = history of diabetes; 0 = no such history)\r\n     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)\r\n     19 restecg: resting electrocardiographic results\r\n        -- Value 0: normal\r\n        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)\r\n        -- Value 2: showing probable or definite left ventricular hypertrophy by Estes\' criteria\r\n     20 ekgmo (month of exercise ECG reading)\r\n     21 ekgday(day of exercise ECG reading)\r\n     22 ekgyr (year of exercise ECG reading)\r\n     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)\r\n     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)\r\n     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)\r\n     28 proto: exercise protocol\r\n          1 = Bruce     \r\n          2 = Kottus\r\n          3 = McHenry\r\n          4 = fast Balke\r\n          5 = Balke\r\n          6 = Noughton \r\n          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was written!)\r\n          8 = bike 125 kpa min/min  \r\n          9 = bike 100 kpa min/min\r\n         10 = bike 75 kpa min/min\r\n         11 = bike 50 kpa min/min\r\n         12 = arm ergometer\r\n     29 thaldur: duration of exercise test in minutes\r\n     30 thaltime: time when ST measure depression was noted\r\n     31 met: mets achieved\r\n     32 thalach: maximum heart rate achieved\r\n     33 thalrest: resting heart rate\r\n     34 tpeakbps: peak exercise blood pressure (first of 2 parts)\r\n     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)\r\n     36 dummy\r\n     37 trestbpd: resting blood pressure\r\n     38 exang: exercise induced angina (1 = yes; 0 = no)\r\n     39 xhypo: (1 = yes; 0 = no)\r\n     40 oldpeak = ST depression induced by exercise relative to rest\r\n     41 slope: the slope of the peak exercise ST segment\r\n        -- Value 1: upsloping\r\n        -- Value 2: flat\r\n        -- Value 3: downsloping\r\n     42 rldv5: height at rest\r\n     43 rldv5e: height at peak exercise\r\n     44 ca: number of major vessels (0-3) colored by flourosopy\r\n     45 restckm: irrelevant\r\n     46 exerckm: irrelevant\r\n     47 restef: rest raidonuclid (sp?) ejection fraction\r\n     48 restwm: rest wall (sp?) motion abnormality\r\n        0 = none\r\n        1 = mild or moderate\r\n        2 = moderate or severe\r\n        3 = akinesis or dyskmem (sp?)\r\n     49 exeref: exercise radinalid (sp?) ejection fraction\r\n     50 exerwm: exercise wall (sp?) motion \r\n     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect\r\n     52 thalsev: not used\r\n     53 thalpul: not used\r\n     54 earlobe: not used\r\n     55 cmo: month of cardiac cath (sp?)  (perhaps "call")\r\n     56 cday: day of cardiac cath (sp?)\r\n     57 cyr: year of cardiac cath (sp?)\r\n     58 num: diagnosis of heart disease (angiographic disease status)\r\n        -- Value 0: < 50% diameter narrowing\r\n        -- Value 1: > 50% diameter narrowing\r\n        (in any major vessel: attributes 59 through 68 are vessels)\r\n     59 lmt\r\n     60 ladprox\r\n     61 laddist\r\n     62 diag\r\n     63 cxmain\r\n     64 ramus\r\n     65 om1\r\n     66 om2\r\n     67 rcaprox\r\n     68 rcadist\r\n     69 lvx1: not used\r\n     70 lvx2: not used\r\n     71 lvx3: not used\r\n     72 lvx4: not used\r\n     73 lvf: not used\r\n     74 cathef: not used\r\n     75 junk: not used\r\n     76 name: last name of patient  (I replaced this with the dummy string "name")', 'citation': None}}

In [32]:
# get the data dictionary
for i in heart_disease.variables: 
    print(i)

name
role
type
demographic
description
units
missing_values

In [35]:
heart_disease.variables.to_csv('./Data Dictionary/UCI_DD.csv')

In [3]:
# 1 is male and 0 is female
df = heart_disease.data.original

In [17]:
# get the data dictionary 
heart_disease.variablesW

In [5]:
df = df.rename(columns = {'age': 'Age', 'sex':'Sex', 'trestbps':'Systolic BP', 'chol':'Cholesterol', 'thalach':'Max Heart Rate', 'num':'Result', 'fbs': 'Fasting Blood Sugar'})

In [6]:

df['Sex'] = df['Sex'].apply(lambda x: 'Male' if x == 1 else 'Female')

In [7]:
df['Data Set'] = 'UC Irvine'

In [8]:
df.columns

Index(['Age', 'Sex', 'cp', 'Systolic BP', 'Cholesterol', 'Fasting Blood Sugar',
       'restecg', 'Max Heart Rate', 'exang', 'oldpeak', 'slope', 'ca', 'thal',
       'Result', 'Data Set'],
      dtype='object')

In [9]:
df[['Age', 'Sex', 'Systolic BP', 'Cholesterol', 'Max Heart Rate', 'Result', 'Fasting Blood Sugar', 'Data Set']]

,Age,Sex,Systolic BP,Cholesterol,Max Heart Rate,Result,Fasting Blood Sugar,Data Set
0,63,Male,145,233,150,0,1,UC Irvine
1,67,Male,160,286,108,2,0,UC Irvine
2,67,Male,120,229,129,1,0,UC Irvine
3,37,Male,130,250,187,0,0,UC Irvine
4,41,Female,130,204,172,0,0,UC Irvine
...,...,...,...,...,...,...,...,...
298,45,Male,110,264,132,1,0,UC Irvine
299,68,Male,144,193,141,2,1,UC Irvine
300,57,Male,130,131,115,3,0,UC Irvine
301,57,Female,130,236,174,1,0,UC Irvine
302,38,Male,138,175,173,0,0,UC Irvine

In [11]:
dd = pd.read_csv('./Data Dictionary/Framingham_DD.csv', header=0)
dd

,Column ID,Column Type,Data Description,Cleaned Data,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,male,Integer (binary),Integer number notating male or female (1=male...,Framingham1,NaN,NaN,NaN
1,Age,Integer,Integer number notating age,NaN,NaN,NaN,NaN
2,education,Integer,Education level of 1 to 4,Cleaned Data,NaN,NaN,NaN
3,currentSmoker,Integer (binary),"Current smoker status (1=current smoker, 0 = n...",1. Added Columns,NaN,NaN,NaN
4,cigsPerDay,Numeric,Integer number notating amount of cigarettes p...,Column IDS,Column Type,Data Description,Process
5,BPMeds,Integer (binary),Integer number notating blood pressur medicati...,Sex,Char,Character description of whether the individua...,IF statement from Male column. Converted 0's t...
6,prevalentStroke,Integer (binary),"Prevalent stroke status (1=prevalent stroke, 0...",Max Heart Rate,Float,Calculation for individual's maximum heart rate,Formula: 208-0.7*HR - See references for formu...
7,prevalentHyp,Integer (binary),"Prevalent hyp status (1=prevalent hyp, 0 = not...",Fasting Blood Sugar,Integer (binary),Indication of whether the patient's gluocse le...,IF statement from glucose column. 1 if glucose...
8,diabetes,Integer (binary),Integer number notating diabetes or no diabet...,Data Set,Char,Indication of data set of origin,Written statement of data set (Framingham for ...
9,Cholesterol,Integer,Integer number notating cholesterol level,NaN,NaN,NaN,NaN
10,sysBP,Float,Systolic blood pressure measurement,2. Remove Columns - Columns not needed for dat...,NaN,NaN,NaN
11,diaBP,Float,Diastolic blood presure measurement,Male,NaN,NaN,NaN
12,BMI,Float,Body mass index measurement,education,NaN,NaN,NaN
13,heartRate,Integer,Heart rate measurement,currentSmoker,NaN,NaN,NaN
14,Glucose,Integer,Glucose level measurement,cigsPerDay,NaN,NaN,NaN
15,Result,Integer (binary),Integer number notating heart disease (1=heart...,BPMeds,NaN,NaN,NaN
16,NaN,NaN,NaN,prevalentStroke,NaN,NaN,NaN
17,NaN,NaN,NaN,prevalentHyp,NaN,NaN,NaN
18,NaN,NaN,NaN,diabetes,NaN,NaN,NaN
19,NaN,NaN,NaN,diaBP,NaN,NaN,NaN
20,NaN,NaN,NaN,BMI,NaN,NaN,NaN
21,NaN,NaN,NaN,glucose,NaN,NaN,NaN